[package]
name = "blethrs"
version = "0.1.1"
authors = ["Adam Greig <adam@adamgreig.com>"]

[dependencies]
cortex-m = "0.5.2"
cortex-m-rt = "0.5.1"
cortex-m-semihosting = "0.3.0"
panic-semihosting = "0.3.0"
panic-abort = "0.2.0"
byteorder = { version = "1.2.2", default-features = false }

[build-dependencies]
built = "0.2.3"

[dependencies.smoltcp]
git = "https://github.com/m-labs/smoltcp"
rev = "cd893e6a"
default-features = false
features = ["proto-ipv4", "socket-tcp"]

[dependencies.stm32f4]
version = "0.2.0"
features = ["stm32f407", "rt"]

[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
debug = true
lto = true
codegen-units = 1
incremental = false
