[package]
name = "blethrs"
version = "0.1.0"
authors = ["Adam Greig <adam@adamgreig.com>"]

[dependencies]
cortex-m = "0.4.3"
cortex-m-semihosting = "0.2.0"
vcell = "0.1.0"

[dependencies.cortex-m-rt]
version = "0.3.14"
features = ["abort-on-panic"]

[dependencies.smoltcp]
git = "https://github.com/m-labs/smoltcp"
rev = "cd893e6a"
default-features = false
features = ["proto-ipv4", "socket-tcp", "socket-udp"]

[dependencies.managed]
version = "0.6.1"
default-features = false

[dependencies.stm32f4]
path = "/home/adam/Projects/stm32-rs/stm32f4"
features = ["stm32f407", "rt"]

[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
debug = true
lto = true
